import type { Config } from 'tailwindcss'

export default {
  content: [
    './src/components/**/*.{js,vue,ts}',
    './src/layouts/**/*.vue',
    './src/pages/**/*.vue',
    './src/plugins/**/*.{js,ts}',
    './src/app.vue',
    './nuxt.config.{js,ts}',
    './vuetify.config.{js,ts}',
    './*.{mjs,js,ts}',
  ],
  important: true,
  corePlugins: [
    'margin',
    'padding',
    'display',
    'flex',
    'flexDirection',
    'flexWrap',
    'flexGrow',
    'flexShrink',
    'flexBasis',
    'alignContent',
    'alignItems',
    'gap',
  ],
  theme: {
    extend: {},
    spacing: {
      0: '0',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      13: '52px',
      14: '56px',
      15: '60px',
      16: '64px',
    },
    screens: {
      xs: { min: '340px' },
      sm: { min: '540px' },
      md: { min: '800px' },
      lg: { min: '1280px' },
    },
  },
  plugins: [],
} satisfies Config
